### ISSUE TITLE
Request: Documentation on how to start PingoMeter when computer starts

### ISSUE THREAD

**Issue by Arc-E-Tect** [EFLFE/PingoMeter#15]
Hi,

I love the little tool. Have it installed on the PCs of my sons, so they know whether our internet connection is suffering from latency problems or it is just the Fortnite and League of Legends game servers.

It would be nice to have it start when the PC starts

**Comment by nakami** [comment]
Hey,

this might help:

1. Create a shortcut of `PingoMeter.exe`
2. Press Win+R to open the "Run"-dialog window
3. In the "Run"-dialog window type `shell:startup` and hit Enter (A new Explorer window will open up with the Startup directory)
4. Put the shortcut of `PingoMeter.exe` in said directory
5.

**Comment by Arc-E-Tect** [comment]
Oh cool. That's the only startup directory I hadn't tried.

**Comment by nakami** [comment]
Added this to README.md in Pull Request https://github.com/EFLFE/PingoMeter/pull/16

**Comment by EFLFE** [comment]
Merged. Sorry for the wait 😅
