### ISSUE TITLE
Feature Request: Instead of Graph, Add Numbers on System Tray

### ISSUE THREAD

**Issue by 8227846265** [EFLFE/PingoMeter#4]
Hello, I would like to suggest giving an option to see numbers for the ping instead of a graph.

Wherein:
If ping is good:
- Background Color: Green
- Text Color: White

If ping is normal:
- Background Color: Orange
- Text Color: Black

If ping is bad:
- Background Color: Red
- Text Color: White

The number that will show is based on the average ping per minute.

That way, user can easily get an idea if their ping gets high as graph is less noticeable and the current notification settings only applies when your internet connection get lost but not when there's an internet speed degradation.

This is highly useful for VPNs wherein the pings can change anytime due to VPN server performance varies per hour.

Note: On VPN, internet speed degradation mean High Ping & Lower Bandwidth.

Sample Image: (Based on Temperature Monitor App for Windows)
![image](https://user-images.githubusercontent.com/66582769/91545133-45c02880-e953-11ea-9455-75bdccf10f99.png)

**Comment by EFLFE** [comment]
Hello. The task does not seem to be very difficult. I just need to think about how to draw a three-digit number.

**Comment by 8227846265** [comment]
The new version solves this.
