### ISSUE TITLE
Feature Request: Alarm sound

### ISSUE THREAD

**Issue by hoasis2** [EFLFE/PingoMeter#5]
I'd like to set audio alarms instead of the taskbar notifications.

Thanks for this nice program. 👍
Cheers!

**Comment by EFLFE** [comment]
Hi, thanks)

> I'd like to set audio alarms instead of the taskbar notifications.

Okay, let me do it :thinking:

**Comment by EFLFE** [comment]
It seems to be working. You can try it:

https://github.com/EFLFE/PingoMeter/releases/tag/0.9.6

**Comment by hoasis2** [comment]
Yes, here it also works. Thank you. :)
