### ISSUE TITLE
Feature request:  "Open automatically after you log into the computer"

### ISSUE THREAD

**Issue by N3ars** [EFLFE/PingoMeter#7]
Hey there, very nice program helped a lot ! thank you !
Everything is in title if there is a way to add "Open automatically after you log into the computer" button could be great !
that's it, thanks.

**Comment by bersbersbers** [comment]
<kbd>Win</kbd>-<kbd>R</kbd> - `shell:startup` - Enter - Right click - New - Shortcut - Browse... - (Find Pingometer.exe) - Next - Finish.
